development:
  adapter: postgresql
  encoding: unicode
  database: blocipedia-example_development
  pool: 5
  username: sashafklein
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: blocipedia-example_test
  pool: 5
  username: sashafklein
  password: